POST http://localhost:3333/courses
Content-Type: application/json

{
  "title": "Curso de Docker 3"
}

###

GET http://localhost:3333/courses

###
GET http://localhost:3333/courses?orderBy=title

###

GET http://localhost:3333/courses/443ede8a-c7e4-4273-b463-7f292c6887bb